# Generated by Django 2.0.6 on 2019-01-03 21:52

from django.db import migrations, models
import uploadimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadimage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='image',
            field=models.ImageField(upload_to=uploadimage.models.rename_uploaded_filename, verbose_name='Uploaded image'),
        ),
    ]
